name: Run Journey Tests on GitHub

permissions:
  checks: write
  pull-requests: write

on:
  workflow_dispatch:
  workflow_call:

jobs:
  matrix:
    name: ${{ matrix.project }} (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        include:
          - os: macos-latest
            project: chrome-mac
            browsers: chromium chrome
          - os: macos-latest
            project: safari-mac
            browsers: webkit
          - os: macos-latest
            project: safari-ios
            browsers: webkit
          - os: windows-latest
            project: chrome-windows
            browsers: chromium chrome
          - os: windows-latest
            project: edge-windows
            browsers: chromium msedge
          - os: ubuntu-latest
            project: chrome-android
            browsers: chromium
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright browsers
        run: npx playwright install --with-deps ${{ matrix.browsers }}
        shell: bash
      - name: Run journey tests (${{ matrix.project }})
        env:
          EPR_USER_EMAIL: ${{ secrets.EPR_USER_EMAIL }}
          EPR_USER_PASSWORD: ${{ secrets.EPR_USER_PASSWORD }}
        run: npx playwright test --project=setup --project=${{ matrix.project }}
        shell: bash
      - name: Upload Playwright artefacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.project }}-${{ matrix.os }}
          path: |
            test-results/
            allure-results/
